# Generated by Django 5.1.5 on 2025-02-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonneesCapteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidite', models.FloatField()),
                ('pression', models.FloatField()),
                ('qualite_air', models.FloatField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
